import _ from 'lodash';

export const tags: string[] = [
  'Ação',
  'Aventura',
  'Boys Love',
  'Comédia',
  'Cyberpunk',
  'Drama',
  'Ecchi',
  'Escolar',
  'Esporte',
  'Fantasia',
  'Filme',
  'Harem',
  'Histórico',
  'Horror',
  'Jogo',
  'Josei',
  'Magia',
  'Mecha',
  'Militar',
  'Mistério',
  'Música',
  'Paródia',
  'Policial',
  'Pós-apocalíptico',
  'Romance',
  'Sci-Fi',
  'Seinei',
  'Shoujo',
  'Shounen',
  'Slice of Life',
  'Sobrenatural',
  'Superpoderes',
  'Thriller',
  'Vampiros',
  'Zumbi',
];

export const getTagPath = (tag: string, baseUrl?: string): string =>
  `${baseUrl}tag/${_.kebabCase(tag)}`;
