name: GitHub Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        uses: xmflsct/action-publish-gatsby@v1
        with:
          publishBranch: 'main'
          token: ${{ secrets.TOKEN }}
