name: Application Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Deploy
        uses: enriikke/gatsby-gh-pages-action@v2.2.0
        with:
          access-token: ${{ secrets.TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
