name: GitHub Pages Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Config
        run : |
          git config --global user.email "alan_f_jantz@hotmail.com"
          git config --global user.name "alanjantz"
        
      - name: Install
        run: yarn
        
      - name: Build and Deploy
        run: |
          gatsby build --prefix-paths
          gh-pages -d public -b gh-pages -r 'https://${{ secrets.TOKEN }}@github.com/komorebi.git'
          
