name: GitHub Pages Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Config
        run: |
          git config --global user.email "alan_f_jantz@hotmail.com"
          git config --global user.name "alanjantz"
          yarn global add gatsby-cli
          gatsby telemetry --disable

      - name: Install
        run: yarn

      - name: Run tests
        run: yarn tests

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn deploy
